# Generated by Django 2.2.3 on 2019-07-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mackta_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
