# Generated by Django 2.2.4 on 2019-08-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mackta_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traindata7',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trantype', models.TextField(blank=True, db_column='TranType', null=True)),
                ('waytype', models.TextField(blank=True, db_column='WayType', null=True)),
                ('trainnum', models.IntegerField(blank=True, db_column='TrainNum', null=True)),
                ('traintype', models.TextField(blank=True, db_column='TrainType', null=True)),
                ('depcity', models.TextField(blank=True, db_column='DepCity', null=True)),
                ('arrcity', models.TextField(blank=True, db_column='ArrCity', null=True)),
                ('deptime', models.TextField(blank=True, db_column='DepTime', null=True)),
                ('arrtime', models.TextField(blank=True, db_column='ArrTime', null=True)),
                ('month', models.IntegerField(blank=True, db_column='Month', null=True)),
                ('day', models.IntegerField(blank=True, db_column='Day', null=True)),
            ],
            options={
                'db_table': 'TrainData7',
                'managed': True,
            },
        ),
    ]
