# Generated by Django 2.2.3 on 2019-07-18 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mackta_api', '0002_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
    ]
