# Generated by Django 2.2.3 on 2019-08-05 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mackta_api', '0002_traindata7'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='traindata7',
            options={'managed': False},
        ),
    ]
