# Generated by Django 2.2.3 on 2019-08-01 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mackta_api', '0004_profilefeeditem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileFeedItem',
        ),
    ]
